### ISSUE TITLE
Derive hostname from OpenAPI schema

### ISSUE THREAD

**Issue by zeke** [crowdin-node/crowdin-node#4]
Currently `hostname` is an option to the factory function, but we should just read it directly from the schema. It's in there:

```yml
servers:
  -
    url: '{protocol}://{host}/api/v2'
    variables:
      protocol:
        enum:
          - https
          - http
        default: https
      host:
        default: api.crowdin.com
```

Something like this could work:

```js
const server = servers[0]
const basepath = pupa(server.url, {
  protocol: server.variables.protocol.default, 
  host: server.variables.host.default
})
```
